[package]
name = "ellipsis-client"
version = "0.1.3"
edition = "2021"
description = "Lightweight interface for interacting with the Solana blockchain"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
bs58 = "0.4.0"
solana-program = "1.10.32"
thiserror = "1.0"
solana-logger = "1.10.32"
solana-program-test = "1.10.32"
solana-transaction-status = "1.14.5"
solana-sdk = "1.10.32"
solana-client = "1.10.32"
async-trait = "0.1.52"
tokio = { version = "1.6", features = ["macros"] }
anyhow = "1.0.52"
bincode = "1.3.3"
